# TCL File Generated by Component Editor 13.0sp1
# Fri Jul 05 22:27:30 EDT 2013
# DO NOT MODIFY


# 
# dma_dispatcher "dma_dispatcher" v1.0
# RSF 2013.07.05.22:27:30
# 
# 

# 
# request TCL package from ACDS 13.1
# 
package require -exact qsys 13.1


# 
# module dma_dispatcher
# 
set_module_property DESCRIPTION ""
set_module_property NAME dma_dispatcher
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR RSF
set_module_property DISPLAY_NAME dma_dispatcher
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL dma_dispatcher
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file dma_dispatcher.v VERILOG PATH dma_dispatcher.v TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL dma_dispatcher
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file dma_dispatcher.v VERILOG PATH dma_dispatcher.v


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point csr
# 
add_interface csr avalon end
set_interface_property csr addressUnits WORDS
set_interface_property csr associatedClock clock
set_interface_property csr associatedReset reset
set_interface_property csr bitsPerSymbol 8
set_interface_property csr burstOnBurstBoundariesOnly false
set_interface_property csr burstcountUnits WORDS
set_interface_property csr explicitAddressSpan 0
set_interface_property csr holdTime 0
set_interface_property csr linewrapBursts false
set_interface_property csr maximumPendingReadTransactions 0
set_interface_property csr readLatency 0
set_interface_property csr readWaitTime 1
set_interface_property csr setupTime 0
set_interface_property csr timingUnits Cycles
set_interface_property csr writeWaitTime 0
set_interface_property csr ENABLED true
set_interface_property csr EXPORT_OF ""
set_interface_property csr PORT_NAME_MAP ""
set_interface_property csr SVD_ADDRESS_GROUP ""

add_interface_port csr avs_csr_read read Input 1
add_interface_port csr avs_csr_address address Input 3
add_interface_port csr avs_csr_readdata readdata Output 32
set_interface_assignment csr embeddedsw.configuration.isFlash 0
set_interface_assignment csr embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment csr embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment csr embeddedsw.configuration.isPrintableDevice 0


# 
# connection point dma_req
# 
add_interface dma_req avalon_streaming end
set_interface_property dma_req associatedClock clock
set_interface_property dma_req associatedReset reset
set_interface_property dma_req dataBitsPerSymbol 128
set_interface_property dma_req errorDescriptor ""
set_interface_property dma_req firstSymbolInHighOrderBits true
set_interface_property dma_req maxChannel 0
set_interface_property dma_req readyLatency 0
set_interface_property dma_req ENABLED true
set_interface_property dma_req EXPORT_OF ""
set_interface_property dma_req PORT_NAME_MAP ""
set_interface_property dma_req SVD_ADDRESS_GROUP ""

add_interface_port dma_req asi_dma_req_data data Input 128
add_interface_port dma_req asi_dma_req_valid valid Input 1
add_interface_port dma_req asi_dma_req_ready ready Output 1


# 
# connection point f2h_dma_write_cmd
# 
add_interface f2h_dma_write_cmd avalon_streaming start
set_interface_property f2h_dma_write_cmd associatedClock clock
set_interface_property f2h_dma_write_cmd associatedReset reset
set_interface_property f2h_dma_write_cmd dataBitsPerSymbol 256
set_interface_property f2h_dma_write_cmd errorDescriptor ""
set_interface_property f2h_dma_write_cmd firstSymbolInHighOrderBits true
set_interface_property f2h_dma_write_cmd maxChannel 0
set_interface_property f2h_dma_write_cmd readyLatency 0
set_interface_property f2h_dma_write_cmd ENABLED true
set_interface_property f2h_dma_write_cmd EXPORT_OF ""
set_interface_property f2h_dma_write_cmd PORT_NAME_MAP ""
set_interface_property f2h_dma_write_cmd SVD_ADDRESS_GROUP ""

add_interface_port f2h_dma_write_cmd aso_f2h_dma_write_cmd_data data Output 256
add_interface_port f2h_dma_write_cmd aso_f2h_dma_write_cmd_valid valid Output 1
add_interface_port f2h_dma_write_cmd aso_f2h_dma_write_cmd_ready ready Input 1


# 
# connection point f2h_dma_write_rsp
# 
add_interface f2h_dma_write_rsp avalon_streaming end
set_interface_property f2h_dma_write_rsp associatedClock clock
set_interface_property f2h_dma_write_rsp associatedReset reset
set_interface_property f2h_dma_write_rsp dataBitsPerSymbol 256
set_interface_property f2h_dma_write_rsp errorDescriptor ""
set_interface_property f2h_dma_write_rsp firstSymbolInHighOrderBits true
set_interface_property f2h_dma_write_rsp maxChannel 0
set_interface_property f2h_dma_write_rsp readyLatency 0
set_interface_property f2h_dma_write_rsp ENABLED true
set_interface_property f2h_dma_write_rsp EXPORT_OF ""
set_interface_property f2h_dma_write_rsp PORT_NAME_MAP ""
set_interface_property f2h_dma_write_rsp SVD_ADDRESS_GROUP ""

add_interface_port f2h_dma_write_rsp asi_f2h_dma_write_rsp_data data Input 256
add_interface_port f2h_dma_write_rsp asi_f2h_dma_write_rsp_valid valid Input 1
add_interface_port f2h_dma_write_rsp asi_f2h_dma_write_rsp_ready ready Output 1


# 
# connection point f2h_dma_read_cmd
# 
add_interface f2h_dma_read_cmd avalon_streaming start
set_interface_property f2h_dma_read_cmd associatedClock clock
set_interface_property f2h_dma_read_cmd associatedReset reset
set_interface_property f2h_dma_read_cmd dataBitsPerSymbol 256
set_interface_property f2h_dma_read_cmd errorDescriptor ""
set_interface_property f2h_dma_read_cmd firstSymbolInHighOrderBits true
set_interface_property f2h_dma_read_cmd maxChannel 0
set_interface_property f2h_dma_read_cmd readyLatency 0
set_interface_property f2h_dma_read_cmd ENABLED true
set_interface_property f2h_dma_read_cmd EXPORT_OF ""
set_interface_property f2h_dma_read_cmd PORT_NAME_MAP ""
set_interface_property f2h_dma_read_cmd SVD_ADDRESS_GROUP ""

add_interface_port f2h_dma_read_cmd aso_f2h_dma_read_cmd_data data Output 256
add_interface_port f2h_dma_read_cmd aso_f2h_dma_read_cmd_valid valid Output 1
add_interface_port f2h_dma_read_cmd aso_f2h_dma_read_cmd_ready ready Input 1


# 
# connection point f2h_dma_read_rsp
# 
add_interface f2h_dma_read_rsp avalon_streaming end
set_interface_property f2h_dma_read_rsp associatedClock clock
set_interface_property f2h_dma_read_rsp associatedReset reset
set_interface_property f2h_dma_read_rsp dataBitsPerSymbol 256
set_interface_property f2h_dma_read_rsp errorDescriptor ""
set_interface_property f2h_dma_read_rsp firstSymbolInHighOrderBits true
set_interface_property f2h_dma_read_rsp maxChannel 0
set_interface_property f2h_dma_read_rsp readyLatency 0
set_interface_property f2h_dma_read_rsp ENABLED true
set_interface_property f2h_dma_read_rsp EXPORT_OF ""
set_interface_property f2h_dma_read_rsp PORT_NAME_MAP ""
set_interface_property f2h_dma_read_rsp SVD_ADDRESS_GROUP ""

add_interface_port f2h_dma_read_rsp asi_f2h_dma_read_rsp_data data Input 256
add_interface_port f2h_dma_read_rsp asi_f2h_dma_read_rsp_valid valid Input 1
add_interface_port f2h_dma_read_rsp asi_f2h_dma_read_rsp_ready ready Output 1


# 
# connection point h2f_dma_write_cmd
# 
add_interface h2f_dma_write_cmd avalon_streaming start
set_interface_property h2f_dma_write_cmd associatedClock clock
set_interface_property h2f_dma_write_cmd associatedReset reset
set_interface_property h2f_dma_write_cmd dataBitsPerSymbol 256
set_interface_property h2f_dma_write_cmd errorDescriptor ""
set_interface_property h2f_dma_write_cmd firstSymbolInHighOrderBits true
set_interface_property h2f_dma_write_cmd maxChannel 0
set_interface_property h2f_dma_write_cmd readyLatency 0
set_interface_property h2f_dma_write_cmd ENABLED true
set_interface_property h2f_dma_write_cmd EXPORT_OF ""
set_interface_property h2f_dma_write_cmd PORT_NAME_MAP ""
set_interface_property h2f_dma_write_cmd SVD_ADDRESS_GROUP ""

add_interface_port h2f_dma_write_cmd aso_h2f_dma_write_cmd_data data Output 256
add_interface_port h2f_dma_write_cmd aso_h2f_dma_write_cmd_valid valid Output 1
add_interface_port h2f_dma_write_cmd aso_h2f_dma_write_cmd_ready ready Input 1


# 
# connection point h2f_dma_write_rsp
# 
add_interface h2f_dma_write_rsp avalon_streaming end
set_interface_property h2f_dma_write_rsp associatedClock clock
set_interface_property h2f_dma_write_rsp associatedReset reset
set_interface_property h2f_dma_write_rsp dataBitsPerSymbol 256
set_interface_property h2f_dma_write_rsp errorDescriptor ""
set_interface_property h2f_dma_write_rsp firstSymbolInHighOrderBits true
set_interface_property h2f_dma_write_rsp maxChannel 0
set_interface_property h2f_dma_write_rsp readyLatency 0
set_interface_property h2f_dma_write_rsp ENABLED true
set_interface_property h2f_dma_write_rsp EXPORT_OF ""
set_interface_property h2f_dma_write_rsp PORT_NAME_MAP ""
set_interface_property h2f_dma_write_rsp SVD_ADDRESS_GROUP ""

add_interface_port h2f_dma_write_rsp asi_h2f_dma_write_rsp_data data Input 256
add_interface_port h2f_dma_write_rsp asi_h2f_dma_write_rsp_valid valid Input 1
add_interface_port h2f_dma_write_rsp asi_h2f_dma_write_rsp_ready ready Output 1


# 
# connection point h2f_dma_read_cmd
# 
add_interface h2f_dma_read_cmd avalon_streaming start
set_interface_property h2f_dma_read_cmd associatedClock clock
set_interface_property h2f_dma_read_cmd associatedReset reset
set_interface_property h2f_dma_read_cmd dataBitsPerSymbol 256
set_interface_property h2f_dma_read_cmd errorDescriptor ""
set_interface_property h2f_dma_read_cmd firstSymbolInHighOrderBits true
set_interface_property h2f_dma_read_cmd maxChannel 0
set_interface_property h2f_dma_read_cmd readyLatency 0
set_interface_property h2f_dma_read_cmd ENABLED true
set_interface_property h2f_dma_read_cmd EXPORT_OF ""
set_interface_property h2f_dma_read_cmd PORT_NAME_MAP ""
set_interface_property h2f_dma_read_cmd SVD_ADDRESS_GROUP ""

add_interface_port h2f_dma_read_cmd aso_h2f_dma_read_cmd_data data Output 256
add_interface_port h2f_dma_read_cmd aso_h2f_dma_read_cmd_valid valid Output 1
add_interface_port h2f_dma_read_cmd aso_h2f_dma_read_cmd_ready ready Input 1


# 
# connection point h2f_dma_read_rsp
# 
add_interface h2f_dma_read_rsp avalon_streaming end
set_interface_property h2f_dma_read_rsp associatedClock clock
set_interface_property h2f_dma_read_rsp associatedReset reset
set_interface_property h2f_dma_read_rsp dataBitsPerSymbol 256
set_interface_property h2f_dma_read_rsp errorDescriptor ""
set_interface_property h2f_dma_read_rsp firstSymbolInHighOrderBits true
set_interface_property h2f_dma_read_rsp maxChannel 0
set_interface_property h2f_dma_read_rsp readyLatency 0
set_interface_property h2f_dma_read_rsp ENABLED true
set_interface_property h2f_dma_read_rsp EXPORT_OF ""
set_interface_property h2f_dma_read_rsp PORT_NAME_MAP ""
set_interface_property h2f_dma_read_rsp SVD_ADDRESS_GROUP ""

add_interface_port h2f_dma_read_rsp asi_h2f_dma_read_rsp_data data Input 256
add_interface_port h2f_dma_read_rsp asi_h2f_dma_read_rsp_valid valid Input 1
add_interface_port h2f_dma_read_rsp asi_h2f_dma_read_rsp_ready ready Output 1

