# TCL File Generated by Component Editor 13.0sp1
# Sat Jul 20 19:51:47 EDT 2013
# DO NOT MODIFY


# 
# channel_remover "channel_remover" v1.0
# RSF 2013.07.20.19:51:47
# 
# 

# 
# request TCL package from ACDS 13.1
# 
package require -exact qsys 13.1


# 
# module channel_remover
# 
set_module_property DESCRIPTION ""
set_module_property NAME channel_remover
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR RSF
set_module_property DISPLAY_NAME channel_remover
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL channel_remover
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file channel_remover.v VERILOG PATH channel_remover.v TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL channel_remover
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file channel_remover.v VERILOG PATH channel_remover.v


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point dma_req_src
# 
add_interface dma_req_src avalon_streaming start
set_interface_property dma_req_src associatedClock clock
set_interface_property dma_req_src associatedReset reset
set_interface_property dma_req_src dataBitsPerSymbol 128
set_interface_property dma_req_src errorDescriptor ""
set_interface_property dma_req_src firstSymbolInHighOrderBits true
set_interface_property dma_req_src maxChannel 0
set_interface_property dma_req_src readyLatency 0
set_interface_property dma_req_src ENABLED true
set_interface_property dma_req_src EXPORT_OF ""
set_interface_property dma_req_src PORT_NAME_MAP ""
set_interface_property dma_req_src SVD_ADDRESS_GROUP ""

add_interface_port dma_req_src aso_dma_req_valid valid Output 1
add_interface_port dma_req_src aso_dma_req_ready ready Input 1
add_interface_port dma_req_src aso_dma_req_data data Output 128


# 
# connection point dma_req_snk
# 
add_interface dma_req_snk avalon_streaming end
set_interface_property dma_req_snk associatedClock clock
set_interface_property dma_req_snk associatedReset reset
set_interface_property dma_req_snk dataBitsPerSymbol 128
set_interface_property dma_req_snk errorDescriptor ""
set_interface_property dma_req_snk firstSymbolInHighOrderBits true
set_interface_property dma_req_snk maxChannel 1
set_interface_property dma_req_snk readyLatency 0
set_interface_property dma_req_snk ENABLED true
set_interface_property dma_req_snk EXPORT_OF ""
set_interface_property dma_req_snk PORT_NAME_MAP ""
set_interface_property dma_req_snk SVD_ADDRESS_GROUP ""

add_interface_port dma_req_snk asi_dma_req_data data Input 128
add_interface_port dma_req_snk asi_dma_req_channel channel Input 1
add_interface_port dma_req_snk asi_dma_req_valid valid Input 1
add_interface_port dma_req_snk asi_dma_req_ready ready Output 1

