// mityarm_5csx_dev_board_mm_interconnect_1.v

// This file was auto-generated from altera_merlin_interconnect_wrapper_hw.tcl.  If you edit it your changes
// will probably be lost.
// 
// Generated using ACDS version 13.1 162 at 2014.02.17.18:45:00

`timescale 1 ps / 1 ps
module mityarm_5csx_dev_board_mm_interconnect_1 (
		input  wire        hps_0_h2f_user0_clock_clk,                                  //                                hps_0_h2f_user0_clock.clk
		input  wire        dma_write_master_0_Clock_reset_reset_bridge_in_reset_reset, // dma_write_master_0_Clock_reset_reset_bridge_in_reset.reset
		input  wire [31:0] dma_write_master_0_Data_Write_Master_address,               //                 dma_write_master_0_Data_Write_Master.address
		output wire        dma_write_master_0_Data_Write_Master_waitrequest,           //                                                     .waitrequest
		input  wire [5:0]  dma_write_master_0_Data_Write_Master_burstcount,            //                                                     .burstcount
		input  wire [7:0]  dma_write_master_0_Data_Write_Master_byteenable,            //                                                     .byteenable
		input  wire        dma_write_master_0_Data_Write_Master_write,                 //                                                     .write
		input  wire [63:0] dma_write_master_0_Data_Write_Master_writedata,             //                                                     .writedata
		output wire [28:0] hps_0_f2h_sdram0_data_address,                              //                                hps_0_f2h_sdram0_data.address
		output wire        hps_0_f2h_sdram0_data_write,                                //                                                     .write
		output wire [63:0] hps_0_f2h_sdram0_data_writedata,                            //                                                     .writedata
		output wire [7:0]  hps_0_f2h_sdram0_data_burstcount,                           //                                                     .burstcount
		output wire [7:0]  hps_0_f2h_sdram0_data_byteenable,                           //                                                     .byteenable
		input  wire        hps_0_f2h_sdram0_data_waitrequest                           //                                                     .waitrequest
	);

	wire          dma_write_master_0_data_write_master_translator_avalon_universal_master_0_waitrequest;            // dma_write_master_0_Data_Write_Master_translator_avalon_universal_master_0_agent:av_waitrequest -> dma_write_master_0_Data_Write_Master_translator:uav_waitrequest
	wire    [8:0] dma_write_master_0_data_write_master_translator_avalon_universal_master_0_burstcount;             // dma_write_master_0_Data_Write_Master_translator:uav_burstcount -> dma_write_master_0_Data_Write_Master_translator_avalon_universal_master_0_agent:av_burstcount
	wire   [63:0] dma_write_master_0_data_write_master_translator_avalon_universal_master_0_writedata;              // dma_write_master_0_Data_Write_Master_translator:uav_writedata -> dma_write_master_0_Data_Write_Master_translator_avalon_universal_master_0_agent:av_writedata
	wire   [31:0] dma_write_master_0_data_write_master_translator_avalon_universal_master_0_address;                // dma_write_master_0_Data_Write_Master_translator:uav_address -> dma_write_master_0_Data_Write_Master_translator_avalon_universal_master_0_agent:av_address
	wire          dma_write_master_0_data_write_master_translator_avalon_universal_master_0_lock;                   // dma_write_master_0_Data_Write_Master_translator:uav_lock -> dma_write_master_0_Data_Write_Master_translator_avalon_universal_master_0_agent:av_lock
	wire          dma_write_master_0_data_write_master_translator_avalon_universal_master_0_write;                  // dma_write_master_0_Data_Write_Master_translator:uav_write -> dma_write_master_0_Data_Write_Master_translator_avalon_universal_master_0_agent:av_write
	wire          dma_write_master_0_data_write_master_translator_avalon_universal_master_0_read;                   // dma_write_master_0_Data_Write_Master_translator:uav_read -> dma_write_master_0_Data_Write_Master_translator_avalon_universal_master_0_agent:av_read
	wire   [63:0] dma_write_master_0_data_write_master_translator_avalon_universal_master_0_readdata;               // dma_write_master_0_Data_Write_Master_translator_avalon_universal_master_0_agent:av_readdata -> dma_write_master_0_Data_Write_Master_translator:uav_readdata
	wire          dma_write_master_0_data_write_master_translator_avalon_universal_master_0_debugaccess;            // dma_write_master_0_Data_Write_Master_translator:uav_debugaccess -> dma_write_master_0_Data_Write_Master_translator_avalon_universal_master_0_agent:av_debugaccess
	wire    [7:0] dma_write_master_0_data_write_master_translator_avalon_universal_master_0_byteenable;             // dma_write_master_0_Data_Write_Master_translator:uav_byteenable -> dma_write_master_0_Data_Write_Master_translator_avalon_universal_master_0_agent:av_byteenable
	wire          dma_write_master_0_data_write_master_translator_avalon_universal_master_0_readdatavalid;          // dma_write_master_0_Data_Write_Master_translator_avalon_universal_master_0_agent:av_readdatavalid -> dma_write_master_0_Data_Write_Master_translator:uav_readdatavalid
	wire          rsp_xbar_mux_src_endofpacket;                                                                     // rsp_xbar_mux:src_endofpacket -> dma_write_master_0_Data_Write_Master_translator_avalon_universal_master_0_agent:rp_endofpacket
	wire          rsp_xbar_mux_src_valid;                                                                           // rsp_xbar_mux:src_valid -> dma_write_master_0_Data_Write_Master_translator_avalon_universal_master_0_agent:rp_valid
	wire          rsp_xbar_mux_src_startofpacket;                                                                   // rsp_xbar_mux:src_startofpacket -> dma_write_master_0_Data_Write_Master_translator_avalon_universal_master_0_agent:rp_startofpacket
	wire  [145:0] rsp_xbar_mux_src_data;                                                                            // rsp_xbar_mux:src_data -> dma_write_master_0_Data_Write_Master_translator_avalon_universal_master_0_agent:rp_data
	wire    [0:0] rsp_xbar_mux_src_channel;                                                                         // rsp_xbar_mux:src_channel -> dma_write_master_0_Data_Write_Master_translator_avalon_universal_master_0_agent:rp_channel
	wire          rsp_xbar_mux_src_ready;                                                                           // dma_write_master_0_Data_Write_Master_translator_avalon_universal_master_0_agent:rp_ready -> rsp_xbar_mux:src_ready
	wire          hps_0_f2h_sdram0_data_translator_avalon_universal_slave_0_agent_m0_waitrequest;                   // hps_0_f2h_sdram0_data_translator:uav_waitrequest -> hps_0_f2h_sdram0_data_translator_avalon_universal_slave_0_agent:m0_waitrequest
	wire   [10:0] hps_0_f2h_sdram0_data_translator_avalon_universal_slave_0_agent_m0_burstcount;                    // hps_0_f2h_sdram0_data_translator_avalon_universal_slave_0_agent:m0_burstcount -> hps_0_f2h_sdram0_data_translator:uav_burstcount
	wire   [63:0] hps_0_f2h_sdram0_data_translator_avalon_universal_slave_0_agent_m0_writedata;                     // hps_0_f2h_sdram0_data_translator_avalon_universal_slave_0_agent:m0_writedata -> hps_0_f2h_sdram0_data_translator:uav_writedata
	wire   [31:0] hps_0_f2h_sdram0_data_translator_avalon_universal_slave_0_agent_m0_address;                       // hps_0_f2h_sdram0_data_translator_avalon_universal_slave_0_agent:m0_address -> hps_0_f2h_sdram0_data_translator:uav_address
	wire          hps_0_f2h_sdram0_data_translator_avalon_universal_slave_0_agent_m0_write;                         // hps_0_f2h_sdram0_data_translator_avalon_universal_slave_0_agent:m0_write -> hps_0_f2h_sdram0_data_translator:uav_write
	wire          hps_0_f2h_sdram0_data_translator_avalon_universal_slave_0_agent_m0_lock;                          // hps_0_f2h_sdram0_data_translator_avalon_universal_slave_0_agent:m0_lock -> hps_0_f2h_sdram0_data_translator:uav_lock
	wire          hps_0_f2h_sdram0_data_translator_avalon_universal_slave_0_agent_m0_read;                          // hps_0_f2h_sdram0_data_translator_avalon_universal_slave_0_agent:m0_read -> hps_0_f2h_sdram0_data_translator:uav_read
	wire   [63:0] hps_0_f2h_sdram0_data_translator_avalon_universal_slave_0_agent_m0_readdata;                      // hps_0_f2h_sdram0_data_translator:uav_readdata -> hps_0_f2h_sdram0_data_translator_avalon_universal_slave_0_agent:m0_readdata
	wire          hps_0_f2h_sdram0_data_translator_avalon_universal_slave_0_agent_m0_readdatavalid;                 // hps_0_f2h_sdram0_data_translator:uav_readdatavalid -> hps_0_f2h_sdram0_data_translator_avalon_universal_slave_0_agent:m0_readdatavalid
	wire          hps_0_f2h_sdram0_data_translator_avalon_universal_slave_0_agent_m0_debugaccess;                   // hps_0_f2h_sdram0_data_translator_avalon_universal_slave_0_agent:m0_debugaccess -> hps_0_f2h_sdram0_data_translator:uav_debugaccess
	wire    [7:0] hps_0_f2h_sdram0_data_translator_avalon_universal_slave_0_agent_m0_byteenable;                    // hps_0_f2h_sdram0_data_translator_avalon_universal_slave_0_agent:m0_byteenable -> hps_0_f2h_sdram0_data_translator:uav_byteenable
	wire          hps_0_f2h_sdram0_data_translator_avalon_universal_slave_0_agent_rf_source_endofpacket;            // hps_0_f2h_sdram0_data_translator_avalon_universal_slave_0_agent:rf_source_endofpacket -> hps_0_f2h_sdram0_data_translator_avalon_universal_slave_0_agent_rsp_fifo:in_endofpacket
	wire          hps_0_f2h_sdram0_data_translator_avalon_universal_slave_0_agent_rf_source_valid;                  // hps_0_f2h_sdram0_data_translator_avalon_universal_slave_0_agent:rf_source_valid -> hps_0_f2h_sdram0_data_translator_avalon_universal_slave_0_agent_rsp_fifo:in_valid
	wire          hps_0_f2h_sdram0_data_translator_avalon_universal_slave_0_agent_rf_source_startofpacket;          // hps_0_f2h_sdram0_data_translator_avalon_universal_slave_0_agent:rf_source_startofpacket -> hps_0_f2h_sdram0_data_translator_avalon_universal_slave_0_agent_rsp_fifo:in_startofpacket
	wire  [146:0] hps_0_f2h_sdram0_data_translator_avalon_universal_slave_0_agent_rf_source_data;                   // hps_0_f2h_sdram0_data_translator_avalon_universal_slave_0_agent:rf_source_data -> hps_0_f2h_sdram0_data_translator_avalon_universal_slave_0_agent_rsp_fifo:in_data
	wire          hps_0_f2h_sdram0_data_translator_avalon_universal_slave_0_agent_rf_source_ready;                  // hps_0_f2h_sdram0_data_translator_avalon_universal_slave_0_agent_rsp_fifo:in_ready -> hps_0_f2h_sdram0_data_translator_avalon_universal_slave_0_agent:rf_source_ready
	wire          hps_0_f2h_sdram0_data_translator_avalon_universal_slave_0_agent_rsp_fifo_out_endofpacket;         // hps_0_f2h_sdram0_data_translator_avalon_universal_slave_0_agent_rsp_fifo:out_endofpacket -> hps_0_f2h_sdram0_data_translator_avalon_universal_slave_0_agent:rf_sink_endofpacket
	wire          hps_0_f2h_sdram0_data_translator_avalon_universal_slave_0_agent_rsp_fifo_out_valid;               // hps_0_f2h_sdram0_data_translator_avalon_universal_slave_0_agent_rsp_fifo:out_valid -> hps_0_f2h_sdram0_data_translator_avalon_universal_slave_0_agent:rf_sink_valid
	wire          hps_0_f2h_sdram0_data_translator_avalon_universal_slave_0_agent_rsp_fifo_out_startofpacket;       // hps_0_f2h_sdram0_data_translator_avalon_universal_slave_0_agent_rsp_fifo:out_startofpacket -> hps_0_f2h_sdram0_data_translator_avalon_universal_slave_0_agent:rf_sink_startofpacket
	wire  [146:0] hps_0_f2h_sdram0_data_translator_avalon_universal_slave_0_agent_rsp_fifo_out_data;                // hps_0_f2h_sdram0_data_translator_avalon_universal_slave_0_agent_rsp_fifo:out_data -> hps_0_f2h_sdram0_data_translator_avalon_universal_slave_0_agent:rf_sink_data
	wire          hps_0_f2h_sdram0_data_translator_avalon_universal_slave_0_agent_rsp_fifo_out_ready;               // hps_0_f2h_sdram0_data_translator_avalon_universal_slave_0_agent:rf_sink_ready -> hps_0_f2h_sdram0_data_translator_avalon_universal_slave_0_agent_rsp_fifo:out_ready
	wire          hps_0_f2h_sdram0_data_translator_avalon_universal_slave_0_agent_rdata_fifo_src_valid;             // hps_0_f2h_sdram0_data_translator_avalon_universal_slave_0_agent:rdata_fifo_src_valid -> hps_0_f2h_sdram0_data_translator_avalon_universal_slave_0_agent:rdata_fifo_sink_valid
	wire   [65:0] hps_0_f2h_sdram0_data_translator_avalon_universal_slave_0_agent_rdata_fifo_src_data;              // hps_0_f2h_sdram0_data_translator_avalon_universal_slave_0_agent:rdata_fifo_src_data -> hps_0_f2h_sdram0_data_translator_avalon_universal_slave_0_agent:rdata_fifo_sink_data
	wire          hps_0_f2h_sdram0_data_translator_avalon_universal_slave_0_agent_rdata_fifo_src_ready;             // hps_0_f2h_sdram0_data_translator_avalon_universal_slave_0_agent:rdata_fifo_sink_ready -> hps_0_f2h_sdram0_data_translator_avalon_universal_slave_0_agent:rdata_fifo_src_ready
	wire          cmd_xbar_mux_src_endofpacket;                                                                     // cmd_xbar_mux:src_endofpacket -> hps_0_f2h_sdram0_data_translator_avalon_universal_slave_0_agent:cp_endofpacket
	wire          cmd_xbar_mux_src_valid;                                                                           // cmd_xbar_mux:src_valid -> hps_0_f2h_sdram0_data_translator_avalon_universal_slave_0_agent:cp_valid
	wire          cmd_xbar_mux_src_startofpacket;                                                                   // cmd_xbar_mux:src_startofpacket -> hps_0_f2h_sdram0_data_translator_avalon_universal_slave_0_agent:cp_startofpacket
	wire  [145:0] cmd_xbar_mux_src_data;                                                                            // cmd_xbar_mux:src_data -> hps_0_f2h_sdram0_data_translator_avalon_universal_slave_0_agent:cp_data
	wire    [0:0] cmd_xbar_mux_src_channel;                                                                         // cmd_xbar_mux:src_channel -> hps_0_f2h_sdram0_data_translator_avalon_universal_slave_0_agent:cp_channel
	wire          cmd_xbar_mux_src_ready;                                                                           // hps_0_f2h_sdram0_data_translator_avalon_universal_slave_0_agent:cp_ready -> cmd_xbar_mux:src_ready
	wire          dma_write_master_0_data_write_master_translator_avalon_universal_master_0_agent_cp_endofpacket;   // dma_write_master_0_Data_Write_Master_translator_avalon_universal_master_0_agent:cp_endofpacket -> addr_router:sink_endofpacket
	wire          dma_write_master_0_data_write_master_translator_avalon_universal_master_0_agent_cp_valid;         // dma_write_master_0_Data_Write_Master_translator_avalon_universal_master_0_agent:cp_valid -> addr_router:sink_valid
	wire          dma_write_master_0_data_write_master_translator_avalon_universal_master_0_agent_cp_startofpacket; // dma_write_master_0_Data_Write_Master_translator_avalon_universal_master_0_agent:cp_startofpacket -> addr_router:sink_startofpacket
	wire  [145:0] dma_write_master_0_data_write_master_translator_avalon_universal_master_0_agent_cp_data;          // dma_write_master_0_Data_Write_Master_translator_avalon_universal_master_0_agent:cp_data -> addr_router:sink_data
	wire          dma_write_master_0_data_write_master_translator_avalon_universal_master_0_agent_cp_ready;         // addr_router:sink_ready -> dma_write_master_0_Data_Write_Master_translator_avalon_universal_master_0_agent:cp_ready
	wire          addr_router_src_endofpacket;                                                                      // addr_router:src_endofpacket -> cmd_xbar_demux:sink_endofpacket
	wire          addr_router_src_valid;                                                                            // addr_router:src_valid -> cmd_xbar_demux:sink_valid
	wire          addr_router_src_startofpacket;                                                                    // addr_router:src_startofpacket -> cmd_xbar_demux:sink_startofpacket
	wire  [145:0] addr_router_src_data;                                                                             // addr_router:src_data -> cmd_xbar_demux:sink_data
	wire    [0:0] addr_router_src_channel;                                                                          // addr_router:src_channel -> cmd_xbar_demux:sink_channel
	wire          addr_router_src_ready;                                                                            // cmd_xbar_demux:sink_ready -> addr_router:src_ready
	wire          hps_0_f2h_sdram0_data_translator_avalon_universal_slave_0_agent_rp_endofpacket;                   // hps_0_f2h_sdram0_data_translator_avalon_universal_slave_0_agent:rp_endofpacket -> id_router:sink_endofpacket
	wire          hps_0_f2h_sdram0_data_translator_avalon_universal_slave_0_agent_rp_valid;                         // hps_0_f2h_sdram0_data_translator_avalon_universal_slave_0_agent:rp_valid -> id_router:sink_valid
	wire          hps_0_f2h_sdram0_data_translator_avalon_universal_slave_0_agent_rp_startofpacket;                 // hps_0_f2h_sdram0_data_translator_avalon_universal_slave_0_agent:rp_startofpacket -> id_router:sink_startofpacket
	wire  [145:0] hps_0_f2h_sdram0_data_translator_avalon_universal_slave_0_agent_rp_data;                          // hps_0_f2h_sdram0_data_translator_avalon_universal_slave_0_agent:rp_data -> id_router:sink_data
	wire          hps_0_f2h_sdram0_data_translator_avalon_universal_slave_0_agent_rp_ready;                         // id_router:sink_ready -> hps_0_f2h_sdram0_data_translator_avalon_universal_slave_0_agent:rp_ready
	wire          id_router_src_endofpacket;                                                                        // id_router:src_endofpacket -> rsp_xbar_demux:sink_endofpacket
	wire          id_router_src_valid;                                                                              // id_router:src_valid -> rsp_xbar_demux:sink_valid
	wire          id_router_src_startofpacket;                                                                      // id_router:src_startofpacket -> rsp_xbar_demux:sink_startofpacket
	wire  [145:0] id_router_src_data;                                                                               // id_router:src_data -> rsp_xbar_demux:sink_data
	wire    [0:0] id_router_src_channel;                                                                            // id_router:src_channel -> rsp_xbar_demux:sink_channel
	wire          id_router_src_ready;                                                                              // rsp_xbar_demux:sink_ready -> id_router:src_ready
	wire          cmd_xbar_demux_src0_endofpacket;                                                                  // cmd_xbar_demux:src0_endofpacket -> cmd_xbar_mux:sink0_endofpacket
	wire          cmd_xbar_demux_src0_valid;                                                                        // cmd_xbar_demux:src0_valid -> cmd_xbar_mux:sink0_valid
	wire          cmd_xbar_demux_src0_startofpacket;                                                                // cmd_xbar_demux:src0_startofpacket -> cmd_xbar_mux:sink0_startofpacket
	wire  [145:0] cmd_xbar_demux_src0_data;                                                                         // cmd_xbar_demux:src0_data -> cmd_xbar_mux:sink0_data
	wire    [0:0] cmd_xbar_demux_src0_channel;                                                                      // cmd_xbar_demux:src0_channel -> cmd_xbar_mux:sink0_channel
	wire          cmd_xbar_demux_src0_ready;                                                                        // cmd_xbar_mux:sink0_ready -> cmd_xbar_demux:src0_ready
	wire          rsp_xbar_demux_src0_endofpacket;                                                                  // rsp_xbar_demux:src0_endofpacket -> rsp_xbar_mux:sink0_endofpacket
	wire          rsp_xbar_demux_src0_valid;                                                                        // rsp_xbar_demux:src0_valid -> rsp_xbar_mux:sink0_valid
	wire          rsp_xbar_demux_src0_startofpacket;                                                                // rsp_xbar_demux:src0_startofpacket -> rsp_xbar_mux:sink0_startofpacket
	wire  [145:0] rsp_xbar_demux_src0_data;                                                                         // rsp_xbar_demux:src0_data -> rsp_xbar_mux:sink0_data
	wire    [0:0] rsp_xbar_demux_src0_channel;                                                                      // rsp_xbar_demux:src0_channel -> rsp_xbar_mux:sink0_channel
	wire          rsp_xbar_demux_src0_ready;                                                                        // rsp_xbar_mux:sink0_ready -> rsp_xbar_demux:src0_ready

	altera_merlin_master_translator #(
		.AV_ADDRESS_W                (32),
		.AV_DATA_W                   (64),
		.AV_BURSTCOUNT_W             (6),
		.AV_BYTEENABLE_W             (8),
		.UAV_ADDRESS_W               (32),
		.UAV_BURSTCOUNT_W            (9),
		.USE_READ                    (0),
		.USE_WRITE                   (1),
		.USE_BEGINBURSTTRANSFER      (0),
		.USE_BEGINTRANSFER           (0),
		.USE_CHIPSELECT              (0),
		.USE_BURSTCOUNT              (1),
		.USE_READDATAVALID           (0),
		.USE_WAITREQUEST             (1),
		.USE_READRESPONSE            (0),
		.USE_WRITERESPONSE           (0),
		.AV_SYMBOLS_PER_WORD         (8),
		.AV_ADDRESS_SYMBOLS          (1),
		.AV_BURSTCOUNT_SYMBOLS       (0),
		.AV_CONSTANT_BURST_BEHAVIOR  (1),
		.UAV_CONSTANT_BURST_BEHAVIOR (0),
		.AV_LINEWRAPBURSTS           (0),
		.AV_REGISTERINCOMINGSIGNALS  (0)
	) dma_write_master_0_data_write_master_translator (
		.clk                      (hps_0_h2f_user0_clock_clk),                                                               //                       clk.clk
		.reset                    (dma_write_master_0_Clock_reset_reset_bridge_in_reset_reset),                              //                     reset.reset
		.uav_address              (dma_write_master_0_data_write_master_translator_avalon_universal_master_0_address),       // avalon_universal_master_0.address
		.uav_burstcount           (dma_write_master_0_data_write_master_translator_avalon_universal_master_0_burstcount),    //                          .burstcount
		.uav_read                 (dma_write_master_0_data_write_master_translator_avalon_universal_master_0_read),          //                          .read
		.uav_write                (dma_write_master_0_data_write_master_translator_avalon_universal_master_0_write),         //                          .write
		.uav_waitrequest          (dma_write_master_0_data_write_master_translator_avalon_universal_master_0_waitrequest),   //                          .waitrequest
		.uav_readdatavalid        (dma_write_master_0_data_write_master_translator_avalon_universal_master_0_readdatavalid), //                          .readdatavalid
		.uav_byteenable           (dma_write_master_0_data_write_master_translator_avalon_universal_master_0_byteenable),    //                          .byteenable
		.uav_readdata             (dma_write_master_0_data_write_master_translator_avalon_universal_master_0_readdata),      //                          .readdata
		.uav_writedata            (dma_write_master_0_data_write_master_translator_avalon_universal_master_0_writedata),     //                          .writedata
		.uav_lock                 (dma_write_master_0_data_write_master_translator_avalon_universal_master_0_lock),          //                          .lock
		.uav_debugaccess          (dma_write_master_0_data_write_master_translator_avalon_universal_master_0_debugaccess),   //                          .debugaccess
		.av_address               (dma_write_master_0_Data_Write_Master_address),                                            //      avalon_anti_master_0.address
		.av_waitrequest           (dma_write_master_0_Data_Write_Master_waitrequest),                                        //                          .waitrequest
		.av_burstcount            (dma_write_master_0_Data_Write_Master_burstcount),                                         //                          .burstcount
		.av_byteenable            (dma_write_master_0_Data_Write_Master_byteenable),                                         //                          .byteenable
		.av_write                 (dma_write_master_0_Data_Write_Master_write),                                              //                          .write
		.av_writedata             (dma_write_master_0_Data_Write_Master_writedata),                                          //                          .writedata
		.av_beginbursttransfer    (1'b0),                                                                                    //               (terminated)
		.av_begintransfer         (1'b0),                                                                                    //               (terminated)
		.av_chipselect            (1'b0),                                                                                    //               (terminated)
		.av_read                  (1'b0),                                                                                    //               (terminated)
		.av_readdata              (),                                                                                        //               (terminated)
		.av_readdatavalid         (),                                                                                        //               (terminated)
		.av_lock                  (1'b0),                                                                                    //               (terminated)
		.av_debugaccess           (1'b0),                                                                                    //               (terminated)
		.uav_clken                (),                                                                                        //               (terminated)
		.av_clken                 (1'b1),                                                                                    //               (terminated)
		.uav_response             (2'b00),                                                                                   //               (terminated)
		.av_response              (),                                                                                        //               (terminated)
		.uav_writeresponserequest (),                                                                                        //               (terminated)
		.uav_writeresponsevalid   (1'b0),                                                                                    //               (terminated)
		.av_writeresponserequest  (1'b0),                                                                                    //               (terminated)
		.av_writeresponsevalid    ()                                                                                         //               (terminated)
	);

	altera_merlin_slave_translator #(
		.AV_ADDRESS_W                   (29),
		.AV_DATA_W                      (64),
		.UAV_DATA_W                     (64),
		.AV_BURSTCOUNT_W                (8),
		.AV_BYTEENABLE_W                (8),
		.UAV_BYTEENABLE_W               (8),
		.UAV_ADDRESS_W                  (32),
		.UAV_BURSTCOUNT_W               (11),
		.AV_READLATENCY                 (0),
		.USE_READDATAVALID              (0),
		.USE_WAITREQUEST                (1),
		.USE_UAV_CLKEN                  (0),
		.USE_READRESPONSE               (0),
		.USE_WRITERESPONSE              (0),
		.AV_SYMBOLS_PER_WORD            (8),
		.AV_ADDRESS_SYMBOLS             (0),
		.AV_BURSTCOUNT_SYMBOLS          (0),
		.AV_CONSTANT_BURST_BEHAVIOR     (0),
		.UAV_CONSTANT_BURST_BEHAVIOR    (0),
		.AV_REQUIRE_UNALIGNED_ADDRESSES (0),
		.CHIPSELECT_THROUGH_READLATENCY (0),
		.AV_READ_WAIT_CYCLES            (1),
		.AV_WRITE_WAIT_CYCLES           (0),
		.AV_SETUP_WAIT_CYCLES           (0),
		.AV_DATA_HOLD_CYCLES            (0)
	) hps_0_f2h_sdram0_data_translator (
		.clk                      (hps_0_h2f_user0_clock_clk),                                                        //                      clk.clk
		.reset                    (dma_write_master_0_Clock_reset_reset_bridge_in_reset_reset),                       //                    reset.reset
		.uav_address              (hps_0_f2h_sdram0_data_translator_avalon_universal_slave_0_agent_m0_address),       // avalon_universal_slave_0.address
		.uav_burstcount           (hps_0_f2h_sdram0_data_translator_avalon_universal_slave_0_agent_m0_burstcount),    //                         .burstcount
		.uav_read                 (hps_0_f2h_sdram0_data_translator_avalon_universal_slave_0_agent_m0_read),          //                         .read
		.uav_write                (hps_0_f2h_sdram0_data_translator_avalon_universal_slave_0_agent_m0_write),         //                         .write
		.uav_waitrequest          (hps_0_f2h_sdram0_data_translator_avalon_universal_slave_0_agent_m0_waitrequest),   //                         .waitrequest
		.uav_readdatavalid        (hps_0_f2h_sdram0_data_translator_avalon_universal_slave_0_agent_m0_readdatavalid), //                         .readdatavalid
		.uav_byteenable           (hps_0_f2h_sdram0_data_translator_avalon_universal_slave_0_agent_m0_byteenable),    //                         .byteenable
		.uav_readdata             (hps_0_f2h_sdram0_data_translator_avalon_universal_slave_0_agent_m0_readdata),      //                         .readdata
		.uav_writedata            (hps_0_f2h_sdram0_data_translator_avalon_universal_slave_0_agent_m0_writedata),     //                         .writedata
		.uav_lock                 (hps_0_f2h_sdram0_data_translator_avalon_universal_slave_0_agent_m0_lock),          //                         .lock
		.uav_debugaccess          (hps_0_f2h_sdram0_data_translator_avalon_universal_slave_0_agent_m0_debugaccess),   //                         .debugaccess
		.av_address               (hps_0_f2h_sdram0_data_address),                                                    //      avalon_anti_slave_0.address
		.av_write                 (hps_0_f2h_sdram0_data_write),                                                      //                         .write
		.av_writedata             (hps_0_f2h_sdram0_data_writedata),                                                  //                         .writedata
		.av_burstcount            (hps_0_f2h_sdram0_data_burstcount),                                                 //                         .burstcount
		.av_byteenable            (hps_0_f2h_sdram0_data_byteenable),                                                 //                         .byteenable
		.av_waitrequest           (hps_0_f2h_sdram0_data_waitrequest),                                                //                         .waitrequest
		.av_read                  (),                                                                                 //              (terminated)
		.av_readdata              (64'b0000000000000000000000000000000011011110101011011101111010101101),             //              (terminated)
		.av_begintransfer         (),                                                                                 //              (terminated)
		.av_beginbursttransfer    (),                                                                                 //              (terminated)
		.av_readdatavalid         (1'b0),                                                                             //              (terminated)
		.av_writebyteenable       (),                                                                                 //              (terminated)
		.av_lock                  (),                                                                                 //              (terminated)
		.av_chipselect            (),                                                                                 //              (terminated)
		.av_clken                 (),                                                                                 //              (terminated)
		.uav_clken                (1'b0),                                                                             //              (terminated)
		.av_debugaccess           (),                                                                                 //              (terminated)
		.av_outputenable          (),                                                                                 //              (terminated)
		.uav_response             (),                                                                                 //              (terminated)
		.av_response              (2'b00),                                                                            //              (terminated)
		.uav_writeresponserequest (1'b0),                                                                             //              (terminated)
		.uav_writeresponsevalid   (),                                                                                 //              (terminated)
		.av_writeresponserequest  (),                                                                                 //              (terminated)
		.av_writeresponsevalid    (1'b0)                                                                              //              (terminated)
	);

	altera_merlin_master_agent #(
		.PKT_PROTECTION_H          (136),
		.PKT_PROTECTION_L          (134),
		.PKT_BEGIN_BURST           (129),
		.PKT_BURSTWRAP_H           (121),
		.PKT_BURSTWRAP_L           (121),
		.PKT_BURST_SIZE_H          (124),
		.PKT_BURST_SIZE_L          (122),
		.PKT_BURST_TYPE_H          (126),
		.PKT_BURST_TYPE_L          (125),
		.PKT_BYTE_CNT_H            (120),
		.PKT_BYTE_CNT_L            (110),
		.PKT_ADDR_H                (103),
		.PKT_ADDR_L                (72),
		.PKT_TRANS_COMPRESSED_READ (104),
		.PKT_TRANS_POSTED          (105),
		.PKT_TRANS_WRITE           (106),
		.PKT_TRANS_READ            (107),
		.PKT_TRANS_LOCK            (108),
		.PKT_TRANS_EXCLUSIVE       (109),
		.PKT_DATA_H                (63),
		.PKT_DATA_L                (0),
		.PKT_BYTEEN_H              (71),
		.PKT_BYTEEN_L              (64),
		.PKT_SRC_ID_H              (131),
		.PKT_SRC_ID_L              (131),
		.PKT_DEST_ID_H             (132),
		.PKT_DEST_ID_L             (132),
		.PKT_THREAD_ID_H           (133),
		.PKT_THREAD_ID_L           (133),
		.PKT_CACHE_H               (140),
		.PKT_CACHE_L               (137),
		.PKT_DATA_SIDEBAND_H       (128),
		.PKT_DATA_SIDEBAND_L       (128),
		.PKT_QOS_H                 (130),
		.PKT_QOS_L                 (130),
		.PKT_ADDR_SIDEBAND_H       (127),
		.PKT_ADDR_SIDEBAND_L       (127),
		.PKT_RESPONSE_STATUS_H     (142),
		.PKT_RESPONSE_STATUS_L     (141),
		.PKT_ORI_BURST_SIZE_L      (143),
		.PKT_ORI_BURST_SIZE_H      (145),
		.ST_DATA_W                 (146),
		.ST_CHANNEL_W              (1),
		.AV_BURSTCOUNT_W           (9),
		.SUPPRESS_0_BYTEEN_RSP     (0),
		.ID                        (0),
		.BURSTWRAP_VALUE           (1),
		.CACHE_VALUE               (0),
		.SECURE_ACCESS_BIT         (1),
		.USE_READRESPONSE          (0),
		.USE_WRITERESPONSE         (0)
	) dma_write_master_0_data_write_master_translator_avalon_universal_master_0_agent (
		.clk                     (hps_0_h2f_user0_clock_clk),                                                                        //       clk.clk
		.reset                   (dma_write_master_0_Clock_reset_reset_bridge_in_reset_reset),                                       // clk_reset.reset
		.av_address              (dma_write_master_0_data_write_master_translator_avalon_universal_master_0_address),                //        av.address
		.av_write                (dma_write_master_0_data_write_master_translator_avalon_universal_master_0_write),                  //          .write
		.av_read                 (dma_write_master_0_data_write_master_translator_avalon_universal_master_0_read),                   //          .read
		.av_writedata            (dma_write_master_0_data_write_master_translator_avalon_universal_master_0_writedata),              //          .writedata
		.av_readdata             (dma_write_master_0_data_write_master_translator_avalon_universal_master_0_readdata),               //          .readdata
		.av_waitrequest          (dma_write_master_0_data_write_master_translator_avalon_universal_master_0_waitrequest),            //          .waitrequest
		.av_readdatavalid        (dma_write_master_0_data_write_master_translator_avalon_universal_master_0_readdatavalid),          //          .readdatavalid
		.av_byteenable           (dma_write_master_0_data_write_master_translator_avalon_universal_master_0_byteenable),             //          .byteenable
		.av_burstcount           (dma_write_master_0_data_write_master_translator_avalon_universal_master_0_burstcount),             //          .burstcount
		.av_debugaccess          (dma_write_master_0_data_write_master_translator_avalon_universal_master_0_debugaccess),            //          .debugaccess
		.av_lock                 (dma_write_master_0_data_write_master_translator_avalon_universal_master_0_lock),                   //          .lock
		.cp_valid                (dma_write_master_0_data_write_master_translator_avalon_universal_master_0_agent_cp_valid),         //        cp.valid
		.cp_data                 (dma_write_master_0_data_write_master_translator_avalon_universal_master_0_agent_cp_data),          //          .data
		.cp_startofpacket        (dma_write_master_0_data_write_master_translator_avalon_universal_master_0_agent_cp_startofpacket), //          .startofpacket
		.cp_endofpacket          (dma_write_master_0_data_write_master_translator_avalon_universal_master_0_agent_cp_endofpacket),   //          .endofpacket
		.cp_ready                (dma_write_master_0_data_write_master_translator_avalon_universal_master_0_agent_cp_ready),         //          .ready
		.rp_valid                (rsp_xbar_mux_src_valid),                                                                           //        rp.valid
		.rp_data                 (rsp_xbar_mux_src_data),                                                                            //          .data
		.rp_channel              (rsp_xbar_mux_src_channel),                                                                         //          .channel
		.rp_startofpacket        (rsp_xbar_mux_src_startofpacket),                                                                   //          .startofpacket
		.rp_endofpacket          (rsp_xbar_mux_src_endofpacket),                                                                     //          .endofpacket
		.rp_ready                (rsp_xbar_mux_src_ready),                                                                           //          .ready
		.av_response             (),                                                                                                 // (terminated)
		.av_writeresponserequest (1'b0),                                                                                             // (terminated)
		.av_writeresponsevalid   ()                                                                                                  // (terminated)
	);

	altera_merlin_slave_agent #(
		.PKT_DATA_H                (63),
		.PKT_DATA_L                (0),
		.PKT_BEGIN_BURST           (129),
		.PKT_SYMBOL_W              (8),
		.PKT_BYTEEN_H              (71),
		.PKT_BYTEEN_L              (64),
		.PKT_ADDR_H                (103),
		.PKT_ADDR_L                (72),
		.PKT_TRANS_COMPRESSED_READ (104),
		.PKT_TRANS_POSTED          (105),
		.PKT_TRANS_WRITE           (106),
		.PKT_TRANS_READ            (107),
		.PKT_TRANS_LOCK            (108),
		.PKT_SRC_ID_H              (131),
		.PKT_SRC_ID_L              (131),
		.PKT_DEST_ID_H             (132),
		.PKT_DEST_ID_L             (132),
		.PKT_BURSTWRAP_H           (121),
		.PKT_BURSTWRAP_L           (121),
		.PKT_BYTE_CNT_H            (120),
		.PKT_BYTE_CNT_L            (110),
		.PKT_PROTECTION_H          (136),
		.PKT_PROTECTION_L          (134),
		.PKT_RESPONSE_STATUS_H     (142),
		.PKT_RESPONSE_STATUS_L     (141),
		.PKT_BURST_SIZE_H          (124),
		.PKT_BURST_SIZE_L          (122),
		.PKT_ORI_BURST_SIZE_L      (143),
		.PKT_ORI_BURST_SIZE_H      (145),
		.ST_CHANNEL_W              (1),
		.ST_DATA_W                 (146),
		.AVS_BURSTCOUNT_W          (11),
		.SUPPRESS_0_BYTEEN_CMD     (0),
		.PREVENT_FIFO_OVERFLOW     (1),
		.USE_READRESPONSE          (0),
		.USE_WRITERESPONSE         (0)
	) hps_0_f2h_sdram0_data_translator_avalon_universal_slave_0_agent (
		.clk                     (hps_0_h2f_user0_clock_clk),                                                                  //             clk.clk
		.reset                   (dma_write_master_0_Clock_reset_reset_bridge_in_reset_reset),                                 //       clk_reset.reset
		.m0_address              (hps_0_f2h_sdram0_data_translator_avalon_universal_slave_0_agent_m0_address),                 //              m0.address
		.m0_burstcount           (hps_0_f2h_sdram0_data_translator_avalon_universal_slave_0_agent_m0_burstcount),              //                .burstcount
		.m0_byteenable           (hps_0_f2h_sdram0_data_translator_avalon_universal_slave_0_agent_m0_byteenable),              //                .byteenable
		.m0_debugaccess          (hps_0_f2h_sdram0_data_translator_avalon_universal_slave_0_agent_m0_debugaccess),             //                .debugaccess
		.m0_lock                 (hps_0_f2h_sdram0_data_translator_avalon_universal_slave_0_agent_m0_lock),                    //                .lock
		.m0_readdata             (hps_0_f2h_sdram0_data_translator_avalon_universal_slave_0_agent_m0_readdata),                //                .readdata
		.m0_readdatavalid        (hps_0_f2h_sdram0_data_translator_avalon_universal_slave_0_agent_m0_readdatavalid),           //                .readdatavalid
		.m0_read                 (hps_0_f2h_sdram0_data_translator_avalon_universal_slave_0_agent_m0_read),                    //                .read
		.m0_waitrequest          (hps_0_f2h_sdram0_data_translator_avalon_universal_slave_0_agent_m0_waitrequest),             //                .waitrequest
		.m0_writedata            (hps_0_f2h_sdram0_data_translator_avalon_universal_slave_0_agent_m0_writedata),               //                .writedata
		.m0_write                (hps_0_f2h_sdram0_data_translator_avalon_universal_slave_0_agent_m0_write),                   //                .write
		.rp_endofpacket          (hps_0_f2h_sdram0_data_translator_avalon_universal_slave_0_agent_rp_endofpacket),             //              rp.endofpacket
		.rp_ready                (hps_0_f2h_sdram0_data_translator_avalon_universal_slave_0_agent_rp_ready),                   //                .ready
		.rp_valid                (hps_0_f2h_sdram0_data_translator_avalon_universal_slave_0_agent_rp_valid),                   //                .valid
		.rp_data                 (hps_0_f2h_sdram0_data_translator_avalon_universal_slave_0_agent_rp_data),                    //                .data
		.rp_startofpacket        (hps_0_f2h_sdram0_data_translator_avalon_universal_slave_0_agent_rp_startofpacket),           //                .startofpacket
		.cp_ready                (cmd_xbar_mux_src_ready),                                                                     //              cp.ready
		.cp_valid                (cmd_xbar_mux_src_valid),                                                                     //                .valid
		.cp_data                 (cmd_xbar_mux_src_data),                                                                      //                .data
		.cp_startofpacket        (cmd_xbar_mux_src_startofpacket),                                                             //                .startofpacket
		.cp_endofpacket          (cmd_xbar_mux_src_endofpacket),                                                               //                .endofpacket
		.cp_channel              (cmd_xbar_mux_src_channel),                                                                   //                .channel
		.rf_sink_ready           (hps_0_f2h_sdram0_data_translator_avalon_universal_slave_0_agent_rsp_fifo_out_ready),         //         rf_sink.ready
		.rf_sink_valid           (hps_0_f2h_sdram0_data_translator_avalon_universal_slave_0_agent_rsp_fifo_out_valid),         //                .valid
		.rf_sink_startofpacket   (hps_0_f2h_sdram0_data_translator_avalon_universal_slave_0_agent_rsp_fifo_out_startofpacket), //                .startofpacket
		.rf_sink_endofpacket     (hps_0_f2h_sdram0_data_translator_avalon_universal_slave_0_agent_rsp_fifo_out_endofpacket),   //                .endofpacket
		.rf_sink_data            (hps_0_f2h_sdram0_data_translator_avalon_universal_slave_0_agent_rsp_fifo_out_data),          //                .data
		.rf_source_ready         (hps_0_f2h_sdram0_data_translator_avalon_universal_slave_0_agent_rf_source_ready),            //       rf_source.ready
		.rf_source_valid         (hps_0_f2h_sdram0_data_translator_avalon_universal_slave_0_agent_rf_source_valid),            //                .valid
		.rf_source_startofpacket (hps_0_f2h_sdram0_data_translator_avalon_universal_slave_0_agent_rf_source_startofpacket),    //                .startofpacket
		.rf_source_endofpacket   (hps_0_f2h_sdram0_data_translator_avalon_universal_slave_0_agent_rf_source_endofpacket),      //                .endofpacket
		.rf_source_data          (hps_0_f2h_sdram0_data_translator_avalon_universal_slave_0_agent_rf_source_data),             //                .data
		.rdata_fifo_sink_ready   (hps_0_f2h_sdram0_data_translator_avalon_universal_slave_0_agent_rdata_fifo_src_ready),       // rdata_fifo_sink.ready
		.rdata_fifo_sink_valid   (hps_0_f2h_sdram0_data_translator_avalon_universal_slave_0_agent_rdata_fifo_src_valid),       //                .valid
		.rdata_fifo_sink_data    (hps_0_f2h_sdram0_data_translator_avalon_universal_slave_0_agent_rdata_fifo_src_data),        //                .data
		.rdata_fifo_src_ready    (hps_0_f2h_sdram0_data_translator_avalon_universal_slave_0_agent_rdata_fifo_src_ready),       //  rdata_fifo_src.ready
		.rdata_fifo_src_valid    (hps_0_f2h_sdram0_data_translator_avalon_universal_slave_0_agent_rdata_fifo_src_valid),       //                .valid
		.rdata_fifo_src_data     (hps_0_f2h_sdram0_data_translator_avalon_universal_slave_0_agent_rdata_fifo_src_data),        //                .data
		.m0_response             (2'b00),                                                                                      //     (terminated)
		.m0_writeresponserequest (),                                                                                           //     (terminated)
		.m0_writeresponsevalid   (1'b0)                                                                                        //     (terminated)
	);

	altera_avalon_sc_fifo #(
		.SYMBOLS_PER_BEAT    (1),
		.BITS_PER_SYMBOL     (147),
		.FIFO_DEPTH          (2),
		.CHANNEL_WIDTH       (0),
		.ERROR_WIDTH         (0),
		.USE_PACKETS         (1),
		.USE_FILL_LEVEL      (0),
		.EMPTY_LATENCY       (1),
		.USE_MEMORY_BLOCKS   (0),
		.USE_STORE_FORWARD   (0),
		.USE_ALMOST_FULL_IF  (0),
		.USE_ALMOST_EMPTY_IF (0)
	) hps_0_f2h_sdram0_data_translator_avalon_universal_slave_0_agent_rsp_fifo (
		.clk               (hps_0_h2f_user0_clock_clk),                                                                  //       clk.clk
		.reset             (dma_write_master_0_Clock_reset_reset_bridge_in_reset_reset),                                 // clk_reset.reset
		.in_data           (hps_0_f2h_sdram0_data_translator_avalon_universal_slave_0_agent_rf_source_data),             //        in.data
		.in_valid          (hps_0_f2h_sdram0_data_translator_avalon_universal_slave_0_agent_rf_source_valid),            //          .valid
		.in_ready          (hps_0_f2h_sdram0_data_translator_avalon_universal_slave_0_agent_rf_source_ready),            //          .ready
		.in_startofpacket  (hps_0_f2h_sdram0_data_translator_avalon_universal_slave_0_agent_rf_source_startofpacket),    //          .startofpacket
		.in_endofpacket    (hps_0_f2h_sdram0_data_translator_avalon_universal_slave_0_agent_rf_source_endofpacket),      //          .endofpacket
		.out_data          (hps_0_f2h_sdram0_data_translator_avalon_universal_slave_0_agent_rsp_fifo_out_data),          //       out.data
		.out_valid         (hps_0_f2h_sdram0_data_translator_avalon_universal_slave_0_agent_rsp_fifo_out_valid),         //          .valid
		.out_ready         (hps_0_f2h_sdram0_data_translator_avalon_universal_slave_0_agent_rsp_fifo_out_ready),         //          .ready
		.out_startofpacket (hps_0_f2h_sdram0_data_translator_avalon_universal_slave_0_agent_rsp_fifo_out_startofpacket), //          .startofpacket
		.out_endofpacket   (hps_0_f2h_sdram0_data_translator_avalon_universal_slave_0_agent_rsp_fifo_out_endofpacket),   //          .endofpacket
		.csr_address       (2'b00),                                                                                      // (terminated)
		.csr_read          (1'b0),                                                                                       // (terminated)
		.csr_write         (1'b0),                                                                                       // (terminated)
		.csr_readdata      (),                                                                                           // (terminated)
		.csr_writedata     (32'b00000000000000000000000000000000),                                                       // (terminated)
		.almost_full_data  (),                                                                                           // (terminated)
		.almost_empty_data (),                                                                                           // (terminated)
		.in_empty          (1'b0),                                                                                       // (terminated)
		.out_empty         (),                                                                                           // (terminated)
		.in_error          (1'b0),                                                                                       // (terminated)
		.out_error         (),                                                                                           // (terminated)
		.in_channel        (1'b0),                                                                                       // (terminated)
		.out_channel       ()                                                                                            // (terminated)
	);

	mityarm_5csx_dev_board_mm_interconnect_1_addr_router addr_router (
		.sink_ready         (dma_write_master_0_data_write_master_translator_avalon_universal_master_0_agent_cp_ready),         //      sink.ready
		.sink_valid         (dma_write_master_0_data_write_master_translator_avalon_universal_master_0_agent_cp_valid),         //          .valid
		.sink_data          (dma_write_master_0_data_write_master_translator_avalon_universal_master_0_agent_cp_data),          //          .data
		.sink_startofpacket (dma_write_master_0_data_write_master_translator_avalon_universal_master_0_agent_cp_startofpacket), //          .startofpacket
		.sink_endofpacket   (dma_write_master_0_data_write_master_translator_avalon_universal_master_0_agent_cp_endofpacket),   //          .endofpacket
		.clk                (hps_0_h2f_user0_clock_clk),                                                                        //       clk.clk
		.reset              (dma_write_master_0_Clock_reset_reset_bridge_in_reset_reset),                                       // clk_reset.reset
		.src_ready          (addr_router_src_ready),                                                                            //       src.ready
		.src_valid          (addr_router_src_valid),                                                                            //          .valid
		.src_data           (addr_router_src_data),                                                                             //          .data
		.src_channel        (addr_router_src_channel),                                                                          //          .channel
		.src_startofpacket  (addr_router_src_startofpacket),                                                                    //          .startofpacket
		.src_endofpacket    (addr_router_src_endofpacket)                                                                       //          .endofpacket
	);

	mityarm_5csx_dev_board_mm_interconnect_1_id_router id_router (
		.sink_ready         (hps_0_f2h_sdram0_data_translator_avalon_universal_slave_0_agent_rp_ready),         //      sink.ready
		.sink_valid         (hps_0_f2h_sdram0_data_translator_avalon_universal_slave_0_agent_rp_valid),         //          .valid
		.sink_data          (hps_0_f2h_sdram0_data_translator_avalon_universal_slave_0_agent_rp_data),          //          .data
		.sink_startofpacket (hps_0_f2h_sdram0_data_translator_avalon_universal_slave_0_agent_rp_startofpacket), //          .startofpacket
		.sink_endofpacket   (hps_0_f2h_sdram0_data_translator_avalon_universal_slave_0_agent_rp_endofpacket),   //          .endofpacket
		.clk                (hps_0_h2f_user0_clock_clk),                                                        //       clk.clk
		.reset              (dma_write_master_0_Clock_reset_reset_bridge_in_reset_reset),                       // clk_reset.reset
		.src_ready          (id_router_src_ready),                                                              //       src.ready
		.src_valid          (id_router_src_valid),                                                              //          .valid
		.src_data           (id_router_src_data),                                                               //          .data
		.src_channel        (id_router_src_channel),                                                            //          .channel
		.src_startofpacket  (id_router_src_startofpacket),                                                      //          .startofpacket
		.src_endofpacket    (id_router_src_endofpacket)                                                         //          .endofpacket
	);

	mityarm_5csx_dev_board_mm_interconnect_1_cmd_xbar_demux cmd_xbar_demux (
		.clk                (hps_0_h2f_user0_clock_clk),                                  //       clk.clk
		.reset              (dma_write_master_0_Clock_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.sink_ready         (addr_router_src_ready),                                      //      sink.ready
		.sink_channel       (addr_router_src_channel),                                    //          .channel
		.sink_data          (addr_router_src_data),                                       //          .data
		.sink_startofpacket (addr_router_src_startofpacket),                              //          .startofpacket
		.sink_endofpacket   (addr_router_src_endofpacket),                                //          .endofpacket
		.sink_valid         (addr_router_src_valid),                                      //          .valid
		.src0_ready         (cmd_xbar_demux_src0_ready),                                  //      src0.ready
		.src0_valid         (cmd_xbar_demux_src0_valid),                                  //          .valid
		.src0_data          (cmd_xbar_demux_src0_data),                                   //          .data
		.src0_channel       (cmd_xbar_demux_src0_channel),                                //          .channel
		.src0_startofpacket (cmd_xbar_demux_src0_startofpacket),                          //          .startofpacket
		.src0_endofpacket   (cmd_xbar_demux_src0_endofpacket)                             //          .endofpacket
	);

	mityarm_5csx_dev_board_mm_interconnect_1_cmd_xbar_mux cmd_xbar_mux (
		.clk                 (hps_0_h2f_user0_clock_clk),                                  //       clk.clk
		.reset               (dma_write_master_0_Clock_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.src_ready           (cmd_xbar_mux_src_ready),                                     //       src.ready
		.src_valid           (cmd_xbar_mux_src_valid),                                     //          .valid
		.src_data            (cmd_xbar_mux_src_data),                                      //          .data
		.src_channel         (cmd_xbar_mux_src_channel),                                   //          .channel
		.src_startofpacket   (cmd_xbar_mux_src_startofpacket),                             //          .startofpacket
		.src_endofpacket     (cmd_xbar_mux_src_endofpacket),                               //          .endofpacket
		.sink0_ready         (cmd_xbar_demux_src0_ready),                                  //     sink0.ready
		.sink0_valid         (cmd_xbar_demux_src0_valid),                                  //          .valid
		.sink0_channel       (cmd_xbar_demux_src0_channel),                                //          .channel
		.sink0_data          (cmd_xbar_demux_src0_data),                                   //          .data
		.sink0_startofpacket (cmd_xbar_demux_src0_startofpacket),                          //          .startofpacket
		.sink0_endofpacket   (cmd_xbar_demux_src0_endofpacket)                             //          .endofpacket
	);

	mityarm_5csx_dev_board_mm_interconnect_1_cmd_xbar_demux rsp_xbar_demux (
		.clk                (hps_0_h2f_user0_clock_clk),                                  //       clk.clk
		.reset              (dma_write_master_0_Clock_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.sink_ready         (id_router_src_ready),                                        //      sink.ready
		.sink_channel       (id_router_src_channel),                                      //          .channel
		.sink_data          (id_router_src_data),                                         //          .data
		.sink_startofpacket (id_router_src_startofpacket),                                //          .startofpacket
		.sink_endofpacket   (id_router_src_endofpacket),                                  //          .endofpacket
		.sink_valid         (id_router_src_valid),                                        //          .valid
		.src0_ready         (rsp_xbar_demux_src0_ready),                                  //      src0.ready
		.src0_valid         (rsp_xbar_demux_src0_valid),                                  //          .valid
		.src0_data          (rsp_xbar_demux_src0_data),                                   //          .data
		.src0_channel       (rsp_xbar_demux_src0_channel),                                //          .channel
		.src0_startofpacket (rsp_xbar_demux_src0_startofpacket),                          //          .startofpacket
		.src0_endofpacket   (rsp_xbar_demux_src0_endofpacket)                             //          .endofpacket
	);

	mityarm_5csx_dev_board_mm_interconnect_1_rsp_xbar_mux rsp_xbar_mux (
		.clk                 (hps_0_h2f_user0_clock_clk),                                  //       clk.clk
		.reset               (dma_write_master_0_Clock_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.src_ready           (rsp_xbar_mux_src_ready),                                     //       src.ready
		.src_valid           (rsp_xbar_mux_src_valid),                                     //          .valid
		.src_data            (rsp_xbar_mux_src_data),                                      //          .data
		.src_channel         (rsp_xbar_mux_src_channel),                                   //          .channel
		.src_startofpacket   (rsp_xbar_mux_src_startofpacket),                             //          .startofpacket
		.src_endofpacket     (rsp_xbar_mux_src_endofpacket),                               //          .endofpacket
		.sink0_ready         (rsp_xbar_demux_src0_ready),                                  //     sink0.ready
		.sink0_valid         (rsp_xbar_demux_src0_valid),                                  //          .valid
		.sink0_channel       (rsp_xbar_demux_src0_channel),                                //          .channel
		.sink0_data          (rsp_xbar_demux_src0_data),                                   //          .data
		.sink0_startofpacket (rsp_xbar_demux_src0_startofpacket),                          //          .startofpacket
		.sink0_endofpacket   (rsp_xbar_demux_src0_endofpacket)                             //          .endofpacket
	);

endmodule
