// qsys_vip_mm_interconnect_0.v

// This file was auto-generated from altera_merlin_interconnect_wrapper_hw.tcl.  If you edit it your changes
// will probably be lost.
// 
// Generated using ACDS version 13.1 162 at 2014.02.19.09:56:09

`timescale 1 ps / 1 ps
module qsys_vip_mm_interconnect_0 (
		input  wire        clk_clk_clk,                                      //                                    clk_clk.clk
		input  wire        master_bfm_clk_reset_reset_bridge_in_reset_reset, // master_bfm_clk_reset_reset_bridge_in_reset.reset
		input  wire [31:0] master_bfm_m0_address,                            //                              master_bfm_m0.address
		output wire        master_bfm_m0_waitrequest,                        //                                           .waitrequest
		input  wire [7:0]  master_bfm_m0_burstcount,                         //                                           .burstcount
		input  wire [3:0]  master_bfm_m0_byteenable,                         //                                           .byteenable
		input  wire        master_bfm_m0_read,                               //                                           .read
		output wire [31:0] master_bfm_m0_readdata,                           //                                           .readdata
		output wire        master_bfm_m0_readdatavalid,                      //                                           .readdatavalid
		input  wire        master_bfm_m0_write,                              //                                           .write
		input  wire [31:0] master_bfm_m0_writedata,                          //                                           .writedata
		output wire [19:0] slave_bfm_s0_address,                             //                               slave_bfm_s0.address
		output wire        slave_bfm_s0_write,                               //                                           .write
		output wire        slave_bfm_s0_read,                                //                                           .read
		input  wire [31:0] slave_bfm_s0_readdata,                            //                                           .readdata
		output wire [31:0] slave_bfm_s0_writedata,                           //                                           .writedata
		output wire [7:0]  slave_bfm_s0_burstcount,                          //                                           .burstcount
		output wire [3:0]  slave_bfm_s0_byteenable,                          //                                           .byteenable
		input  wire        slave_bfm_s0_readdatavalid,                       //                                           .readdatavalid
		input  wire        slave_bfm_s0_waitrequest                          //                                           .waitrequest
	);

	wire         master_bfm_m0_translator_avalon_universal_master_0_waitrequest;   // slave_bfm_s0_translator:uav_waitrequest -> master_bfm_m0_translator:uav_waitrequest
	wire   [9:0] master_bfm_m0_translator_avalon_universal_master_0_burstcount;    // master_bfm_m0_translator:uav_burstcount -> slave_bfm_s0_translator:uav_burstcount
	wire  [31:0] master_bfm_m0_translator_avalon_universal_master_0_writedata;     // master_bfm_m0_translator:uav_writedata -> slave_bfm_s0_translator:uav_writedata
	wire  [31:0] master_bfm_m0_translator_avalon_universal_master_0_address;       // master_bfm_m0_translator:uav_address -> slave_bfm_s0_translator:uav_address
	wire         master_bfm_m0_translator_avalon_universal_master_0_lock;          // master_bfm_m0_translator:uav_lock -> slave_bfm_s0_translator:uav_lock
	wire         master_bfm_m0_translator_avalon_universal_master_0_write;         // master_bfm_m0_translator:uav_write -> slave_bfm_s0_translator:uav_write
	wire         master_bfm_m0_translator_avalon_universal_master_0_read;          // master_bfm_m0_translator:uav_read -> slave_bfm_s0_translator:uav_read
	wire  [31:0] master_bfm_m0_translator_avalon_universal_master_0_readdata;      // slave_bfm_s0_translator:uav_readdata -> master_bfm_m0_translator:uav_readdata
	wire         master_bfm_m0_translator_avalon_universal_master_0_debugaccess;   // master_bfm_m0_translator:uav_debugaccess -> slave_bfm_s0_translator:uav_debugaccess
	wire   [3:0] master_bfm_m0_translator_avalon_universal_master_0_byteenable;    // master_bfm_m0_translator:uav_byteenable -> slave_bfm_s0_translator:uav_byteenable
	wire         master_bfm_m0_translator_avalon_universal_master_0_readdatavalid; // slave_bfm_s0_translator:uav_readdatavalid -> master_bfm_m0_translator:uav_readdatavalid

	altera_merlin_master_translator #(
		.AV_ADDRESS_W                (32),
		.AV_DATA_W                   (32),
		.AV_BURSTCOUNT_W             (8),
		.AV_BYTEENABLE_W             (4),
		.UAV_ADDRESS_W               (32),
		.UAV_BURSTCOUNT_W            (10),
		.USE_READ                    (1),
		.USE_WRITE                   (1),
		.USE_BEGINBURSTTRANSFER      (0),
		.USE_BEGINTRANSFER           (0),
		.USE_CHIPSELECT              (0),
		.USE_BURSTCOUNT              (1),
		.USE_READDATAVALID           (1),
		.USE_WAITREQUEST             (1),
		.USE_READRESPONSE            (0),
		.USE_WRITERESPONSE           (0),
		.AV_SYMBOLS_PER_WORD         (4),
		.AV_ADDRESS_SYMBOLS          (1),
		.AV_BURSTCOUNT_SYMBOLS       (0),
		.AV_CONSTANT_BURST_BEHAVIOR  (1),
		.UAV_CONSTANT_BURST_BEHAVIOR (1),
		.AV_LINEWRAPBURSTS           (1),
		.AV_REGISTERINCOMINGSIGNALS  (0)
	) master_bfm_m0_translator (
		.clk                      (clk_clk_clk),                                                      //                       clk.clk
		.reset                    (master_bfm_clk_reset_reset_bridge_in_reset_reset),                 //                     reset.reset
		.uav_address              (master_bfm_m0_translator_avalon_universal_master_0_address),       // avalon_universal_master_0.address
		.uav_burstcount           (master_bfm_m0_translator_avalon_universal_master_0_burstcount),    //                          .burstcount
		.uav_read                 (master_bfm_m0_translator_avalon_universal_master_0_read),          //                          .read
		.uav_write                (master_bfm_m0_translator_avalon_universal_master_0_write),         //                          .write
		.uav_waitrequest          (master_bfm_m0_translator_avalon_universal_master_0_waitrequest),   //                          .waitrequest
		.uav_readdatavalid        (master_bfm_m0_translator_avalon_universal_master_0_readdatavalid), //                          .readdatavalid
		.uav_byteenable           (master_bfm_m0_translator_avalon_universal_master_0_byteenable),    //                          .byteenable
		.uav_readdata             (master_bfm_m0_translator_avalon_universal_master_0_readdata),      //                          .readdata
		.uav_writedata            (master_bfm_m0_translator_avalon_universal_master_0_writedata),     //                          .writedata
		.uav_lock                 (master_bfm_m0_translator_avalon_universal_master_0_lock),          //                          .lock
		.uav_debugaccess          (master_bfm_m0_translator_avalon_universal_master_0_debugaccess),   //                          .debugaccess
		.av_address               (master_bfm_m0_address),                                            //      avalon_anti_master_0.address
		.av_waitrequest           (master_bfm_m0_waitrequest),                                        //                          .waitrequest
		.av_burstcount            (master_bfm_m0_burstcount),                                         //                          .burstcount
		.av_byteenable            (master_bfm_m0_byteenable),                                         //                          .byteenable
		.av_read                  (master_bfm_m0_read),                                               //                          .read
		.av_readdata              (master_bfm_m0_readdata),                                           //                          .readdata
		.av_readdatavalid         (master_bfm_m0_readdatavalid),                                      //                          .readdatavalid
		.av_write                 (master_bfm_m0_write),                                              //                          .write
		.av_writedata             (master_bfm_m0_writedata),                                          //                          .writedata
		.av_beginbursttransfer    (1'b0),                                                             //               (terminated)
		.av_begintransfer         (1'b0),                                                             //               (terminated)
		.av_chipselect            (1'b0),                                                             //               (terminated)
		.av_lock                  (1'b0),                                                             //               (terminated)
		.av_debugaccess           (1'b0),                                                             //               (terminated)
		.uav_clken                (),                                                                 //               (terminated)
		.av_clken                 (1'b1),                                                             //               (terminated)
		.uav_response             (2'b00),                                                            //               (terminated)
		.av_response              (),                                                                 //               (terminated)
		.uav_writeresponserequest (),                                                                 //               (terminated)
		.uav_writeresponsevalid   (1'b0),                                                             //               (terminated)
		.av_writeresponserequest  (1'b0),                                                             //               (terminated)
		.av_writeresponsevalid    ()                                                                  //               (terminated)
	);

	altera_merlin_slave_translator #(
		.AV_ADDRESS_W                   (20),
		.AV_DATA_W                      (32),
		.UAV_DATA_W                     (32),
		.AV_BURSTCOUNT_W                (8),
		.AV_BYTEENABLE_W                (4),
		.UAV_BYTEENABLE_W               (4),
		.UAV_ADDRESS_W                  (32),
		.UAV_BURSTCOUNT_W               (10),
		.AV_READLATENCY                 (0),
		.USE_READDATAVALID              (1),
		.USE_WAITREQUEST                (1),
		.USE_UAV_CLKEN                  (0),
		.USE_READRESPONSE               (0),
		.USE_WRITERESPONSE              (0),
		.AV_SYMBOLS_PER_WORD            (4),
		.AV_ADDRESS_SYMBOLS             (0),
		.AV_BURSTCOUNT_SYMBOLS          (0),
		.AV_CONSTANT_BURST_BEHAVIOR     (0),
		.UAV_CONSTANT_BURST_BEHAVIOR    (0),
		.AV_REQUIRE_UNALIGNED_ADDRESSES (0),
		.CHIPSELECT_THROUGH_READLATENCY (0),
		.AV_READ_WAIT_CYCLES            (1),
		.AV_WRITE_WAIT_CYCLES           (0),
		.AV_SETUP_WAIT_CYCLES           (0),
		.AV_DATA_HOLD_CYCLES            (0)
	) slave_bfm_s0_translator (
		.clk                      (clk_clk_clk),                                                      //                      clk.clk
		.reset                    (master_bfm_clk_reset_reset_bridge_in_reset_reset),                 //                    reset.reset
		.uav_address              (master_bfm_m0_translator_avalon_universal_master_0_address),       // avalon_universal_slave_0.address
		.uav_burstcount           (master_bfm_m0_translator_avalon_universal_master_0_burstcount),    //                         .burstcount
		.uav_read                 (master_bfm_m0_translator_avalon_universal_master_0_read),          //                         .read
		.uav_write                (master_bfm_m0_translator_avalon_universal_master_0_write),         //                         .write
		.uav_waitrequest          (master_bfm_m0_translator_avalon_universal_master_0_waitrequest),   //                         .waitrequest
		.uav_readdatavalid        (master_bfm_m0_translator_avalon_universal_master_0_readdatavalid), //                         .readdatavalid
		.uav_byteenable           (master_bfm_m0_translator_avalon_universal_master_0_byteenable),    //                         .byteenable
		.uav_readdata             (master_bfm_m0_translator_avalon_universal_master_0_readdata),      //                         .readdata
		.uav_writedata            (master_bfm_m0_translator_avalon_universal_master_0_writedata),     //                         .writedata
		.uav_lock                 (master_bfm_m0_translator_avalon_universal_master_0_lock),          //                         .lock
		.uav_debugaccess          (master_bfm_m0_translator_avalon_universal_master_0_debugaccess),   //                         .debugaccess
		.av_address               (slave_bfm_s0_address),                                             //      avalon_anti_slave_0.address
		.av_write                 (slave_bfm_s0_write),                                               //                         .write
		.av_read                  (slave_bfm_s0_read),                                                //                         .read
		.av_readdata              (slave_bfm_s0_readdata),                                            //                         .readdata
		.av_writedata             (slave_bfm_s0_writedata),                                           //                         .writedata
		.av_burstcount            (slave_bfm_s0_burstcount),                                          //                         .burstcount
		.av_byteenable            (slave_bfm_s0_byteenable),                                          //                         .byteenable
		.av_readdatavalid         (slave_bfm_s0_readdatavalid),                                       //                         .readdatavalid
		.av_waitrequest           (slave_bfm_s0_waitrequest),                                         //                         .waitrequest
		.av_begintransfer         (),                                                                 //              (terminated)
		.av_beginbursttransfer    (),                                                                 //              (terminated)
		.av_writebyteenable       (),                                                                 //              (terminated)
		.av_lock                  (),                                                                 //              (terminated)
		.av_chipselect            (),                                                                 //              (terminated)
		.av_clken                 (),                                                                 //              (terminated)
		.uav_clken                (1'b0),                                                             //              (terminated)
		.av_debugaccess           (),                                                                 //              (terminated)
		.av_outputenable          (),                                                                 //              (terminated)
		.uav_response             (),                                                                 //              (terminated)
		.av_response              (2'b00),                                                            //              (terminated)
		.uav_writeresponserequest (1'b0),                                                             //              (terminated)
		.uav_writeresponsevalid   (),                                                                 //              (terminated)
		.av_writeresponserequest  (),                                                                 //              (terminated)
		.av_writeresponsevalid    (1'b0)                                                              //              (terminated)
	);

endmodule
